{% set name = "toro" %}
{% set version = "1.0.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "c5452e477e0d20ec459612a3be9eeed93e8dc5253423b604f73692ce628c6bc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - tornado >=3

test:
  imports:
    - toro

about:
  home: https://github.com/ajdavis/toro/
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Synchronization primitives for Tornado coroutines'
  doc_url: http://toro.readthedocs.org/
  dev_url: http://github.com/ajdavis/toro/

extra:
  recipe-maintainers:
    - pmlandwehr
