appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BOkv2eDyueciOXf643bcUkCYZje8QuOOKxC+tJmI2yPWwqdUU74579LSnJuRsiY+6PuDL8QT4HBZis6x9kK3SQf/Cw5oaXEitIKTDepxLe2K6s+kvxXjXq+GvGJNa5wjzXWC9vT7j3eD7/N5w2D4EbjQ2r2pnlRlQPTeS2xdxVWTb8nPfKaOGls6jUp3fzgUdHPGw49oxgbhRggIoAzxQitt+wxLg3p3VF9inZ94q4fHbZY34EGiTEHCchk1io+5TawYG9za6kpRoQUoo574nX9mW8t1YN6yZ0FxNMP/lLy0B5sFYoo/4q/2YvN5Hi/0sUrp2aQ7G/D7V83fn4vOs3NPfXiqplW2vi1ytQYNG3Rmo+0ko5p0dKruY1JFHk9lsaaJgdrQKHHd1Wsj5IvnWpA8y00XEAiyikKMZDuwE01mlaKM3HR99M3wdwA1n68DYEcY5N0BtITSBVjupKPvVI44A9lbpvoxP2SHUO2raYg4XsRweAWSk+hpJsc2R8GYZzpq6UkvimkLHa1DCoo0nWExaaMl4F4MhHPevBtK25nuibYLw/FJT2hTUvufWxEuVUApVkfXxRmmYEa+zyM0YOQg0RlR95CHLt6wfbkMQbusFE9KbfJx0aQzouG8OgL2aJrz6u31mhc3l3j7xuqxra/Z4kXmtBh9Mn3HHBRPdpA=}
conda_forge_output_validation: true
